User-Signup FE
ISODS-Software-Engineering-Team/ISODS-Web-Competition-FE pull request #7
Opened 2023-04-13 18:12 UTC by emmytran

# What does this PR solve and how
## What is this PR about?
- Front-end for User Signup

## How to run it step by step
Step 1: run
`` npm start ``

Step 2: 
From the URL, type: http://localhost:3000/signup

# Implementation 

Add any implementation details
- New UserSignUp.js file
- Added path ./signup (line 16 + 3 in App.js)
- Added first_name, last_name, email, username, password, re_password params (line 32-46 in Auth.server.js)
- Added password requirement for 8 characters minimum + a special symbol

# Testing
Run `` npm start ``
Then type from the URL, type: http://localhost:3000/signup

# Risk
- 

# Dependencies
- 

# PR Checklist
- [x] Documentation
- [ ] Unit testing passed
- [ ] Code review and discussion
- [x] Approve
- [x] Merge

2023-04-14 09:54 UTC, anthony-le-isods commented
@longnguyen-isods phien ong review giup toi nha, thanks ong

2023-04-14 14:10 UTC, longnguyen-isods commented
Hi Emmy, 

Please fix your signup function on auth.server.js. FE calls only "API_URL_USERS" with the / at the end.
Should be something like this: ``` return axios.post(`${API_URL_USERS}/`, ``` --> it was my bad I didn't give you the API.
Your feature ran well after changing the API call, but instead of return to home page, should we notify user that they need to check their email for activation link?

Thank you!

2023-04-14 20:18 UTC, longnguyen-isods requested changes
Pls check comment above

2023-04-23 14:31 UTC, longnguyen-isods commented on src/Components/Auth/UserSignUp.js
if (...) from line 49 - 52. You need to take it outside the function submitSignUp. Otherwise, it is unreachable.

2023-04-23 14:34 UTC, merged